version: '3.9'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS="ntp1.aliyun.com,ntp2.aliyun.com,ntp3.aliyun.com,ntp4.aliyun.com,time.cloudflare.com,time1.google.com,time2.google.com,time3.google.com,time4.google.com" 
      - LOG_LEVEL=0
      - TZ=Asia/Shanghai
      - NOCLIENTLOG=true
      - ENABLE_NTS=true
